name: Django CI CD

on:
  push:
    branches: ['main']
  pull_request:

jobs:
  build:
    name: Lint and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run flake8
        run: flake8

      - name: Test with coverage and enforce ≥ 80 %
        run: |
          pytest --cov=. \
                 --cov-report=term-missing \
                 --cov-fail-under=80

      - name: Log in to Docker Hub
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          docker build --platform linux/amd64 . \
            --tag ${{ secrets.DOCKERHUB_USERNAME }}/oc-lettings:${{ github.sha }} \
            --tag ${{ secrets.DOCKERHUB_USERNAME }}/oc-lettings:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/oc-lettings:${{ github.sha }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/oc-lettings:latest

  deploy:
    name: Deployment to Render
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Trigger Render deploy via webhook
        run: |
          curl -G \
            --data-urlencode "imgURL=docker.io/caneles/oc-lettings:${{ github.sha }}" \
            "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"
